/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JCsound_Csound */

#ifndef _Included_JCsound_Csound
#define _Included_JCsound_Csound
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: thread */
/*
 * Class:     JCsound_Csound
 * Method:    setCommand
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_JCsound_Csound_setCommand
  (JNIEnv *, jobject, jstring);

/*
 * Class:     JCsound_Csound
 * Method:    run
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JCsound_Csound_run
  (JNIEnv *, jobject);

/*
 * Class:     JCsound_Csound
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JCsound_Csound_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
